# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-15 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180815_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
    ]
